// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24.2.2026, 16:42:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Webdev/classpicker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Webdev/classpicker/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Webdev/classpicker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Webdev/classpicker/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Webdev/classpicker/plugins/**/*.{js,ts,mjs}","C:/Webdev/classpicker/composables/**/*.{js,ts,mjs}","C:/Webdev/classpicker/utils/**/*.{js,ts,mjs}","C:/Webdev/classpicker/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Webdev/classpicker/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Webdev/classpicker/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Webdev/classpicker/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;